import os

class Config:
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'you-will-never-guess' #gets secret key from env var of server running app, managed by devops
    
#do not hardcode secret keys into codebase for security reasons due to risk of accidental exposure
#secret key is an application-wide setting that Flask and its extensions use to cryptographically sign cookies and session data, and to secure form submissions, it is generated by devops or security manager
#secret key is to authenticate, session and cookies data to keep the user signed in and ensure security

